version: '3.8'

services:
  nanobana:
    build: .
    container_name: 3k-nanobana
    ports:
      - "3005:3005"
    volumes:
      - ./data:/usr/src/app/data
    env_file:
      - .env
    restart: unless-stopped
